pipeline {
    agent any

    stages {
        stage('Clonar repositorio') {
            steps {
                git branch: 'master', url: ''
            }
        }
        stage('Instalar dependencias') {
            steps {
                sh 'npm install'
            }
        }
        stage('Executar cypress') {
            steps {
                sh 'NO_COLOR=1 npm run cy:run'
            }
        }
    }
}